# Reescribe los párrafos que Turnitin marcó como IA en el trabajo de lectoescritura,
# corrige erratas y quita frases que parecen comentarios de un revisor pegados en el texto.
# Uso: python reescribir.py original.docx salida.docx
import sys
import docx
from docx.oxml.ns import qn

FULL = {}   # párrafo completo (queda en un solo run sin negrita ni cursiva)
LEAD = {}   # conserva el run inicial en negrita (verbo del objetivo) y cambia el resto

# --- Dedicatoria y agradecimientos
FULL[26] = "A mi esposo. Te fuiste, y aun así sigo sintiendo que caminas conmigo. Este trabajo también es tuyo: en cada página hay algo de lo que vivimos juntos, del amor y de las ganas que compartíamos. Tu recuerdo me sostiene en los días difíciles y me empuja a seguir. Gracias por seguir siendo, de algún modo, la voz que me dice que no me rinda."
FULL[27] = "A mi mamá, que nunca dejó de estar. Por todo lo que se esforzó para que yo pudiera estudiar y por enseñarme, con su ejemplo, a ser responsable y a no soltar las cosas cuando se ponen duras. Mucho de lo que he logrado se lo debo a ella."
FULL[28] = "Este trabajo no es solo fruto de mi esfuerzo. Detrás hay sacrificios de ustedes que casi nunca se ven, y una confianza en mí que nunca me faltó."
FULL[29] = "A los dos, con todo mi cariño, les dedico este logro."
FULL[39] = "Gracias a Dios, por darme fuerzas para terminar este proceso aun en los momentos en que todo se puso cuesta arriba."
FULL[40] = "A mi mamá, otra vez, porque sin ella esto no habría sido posible. Este trabajo también es tuyo, mamá. Detrás de cada página están tus palabras de ánimo, tu paciencia y tu manera de estar siempre ahí. Eres quien más me inspira a seguir."
FULL[41] = "Al profesor Jean Paul, por acompañarme, orientarme y confiar en este trabajo. Su ayuda, en lo académico y en lo humano, me sirvió para ordenar mis ideas y sacar el proyecto adelante."
FULL[42] = "Y a mi esposo, que aunque ya no está, sigue siendo parte de mi vida y de lo que consigo. Pensar en él me dio fuerza en los peores momentos. Este logro también es para honrar su memoria."
FULL[43] = "Gracias a todos por acompañarme hasta aquí."
FULL[167] = "Y recuerda: lo que sana es el amor que das."

# --- Resumen y Abstract
FULL[93] = "En este trabajo revisamos lo que dicen investigaciones recientes sobre cómo se enseña y se aprende a leer y escribir en América Latina, con atención a factores neurobiológicos, pedagógicos, socioculturales y tecnológicos. Nos interesaba ver de qué manera la dislexia, la formación de los docentes, la desigualdad educativa y lo que dejó la pandemia afectan la lectura y la escritura de los estudiantes. La metodología combina una revisión documental de estudios y artículos científicos con una prueba diagnóstica de pseudopalabras, que diseñamos para observar la ruta fonológica, la decodificación y la conciencia fonológica en diez estudiantes de básica."
FULL[94] = "La revisión muestra que la dislexia sigue siendo poco comprendida en las escuelas. La lateralidad cruzada, una conciencia fonológica débil y la poca formación de los docentes en este tema hacen más difícil atender a tiempo las dificultades lectoras. La pandemia, por su parte, amplió las brechas, sobre todo entre los estudiantes de contextos vulnerables, y la alfabetización académica todavía es una tarea pendiente en la formación inicial de maestros. Los estudios revisados reportan buenos resultados con intervenciones multisensoriales, actividades lúdicas y enfoques inclusivos."
FULL[95] = "Concluimos que hacen falta diagnósticos tempranos, estrategias pensadas para cada contexto, capacitación docente continua y políticas que aseguren a todos el acceso a la cultura escrita."
FULL[100] = "This study reviews recent research on how reading and writing are taught and learned in Latin America, looking at neurobiological, pedagogical, sociocultural and technological factors. We wanted to see how dyslexia, teacher training, educational inequality and the aftermath of the pandemic affect students' reading and writing. The method combines a documentary review of studies and scientific articles with a pseudoword diagnostic test that we designed to observe the phonological route, decoding and phonological awareness in ten primary school students."
FULL[101] = "The review shows that dyslexia is still poorly understood in schools. Crossed laterality, weak phonological awareness and limited teacher preparation make it harder to address reading difficulties in time. The pandemic widened existing gaps, especially for students in vulnerable settings, and academic literacy remains an unfinished task in initial teacher education. The studies reviewed report good results with multisensory interventions, play-based activities and inclusive approaches."
FULL[102] = "We conclude that early diagnosis, context-sensitive strategies, ongoing teacher training and policies that guarantee everyone access to written culture are needed."

# --- Introducción
FULL[115] = "Aprender a leer y a escribir abre la puerta a casi todo lo demás en la escuela: al conocimiento, a la manera de pensar y a la participación en una cultura que funciona por escrito. Muchos estudiantes, en especial en América Latina, siguen teniendo dificultades con la lectura y la escritura, y los estudios las asocian con causas neurobiológicas, pedagógicas, sociales y del entorno. La dislexia, una formación docente insuficiente, la inequidad y lo que dejó la pandemia han hecho este aprendizaje todavía más difícil."
FULL[116] = "Lo que queremos entender en este trabajo es cómo pesan esas variables en la forma en que los estudiantes leen y escriben, y qué consecuencias tiene eso para planear la enseñanza. Por eso nos propusimos analizar los factores que intervienen en la enseñanza y el aprendizaje de la lectoescritura, juntando lo que dice la teoría, lo que han encontrado otras investigaciones y lo que observamos al aplicar, como ejercicio piloto, una prueba diagnóstica de pseudopalabras."
FULL[117] = "Las preguntas que guiaron la investigación fueron estas:"
FULL[118] = "¿Qué enfoques pedagógicos y metodológicos han dado mejores resultados para fortalecer la lectoescritura en contextos educativos vulnerables?"
FULL[119] = "¿Cómo se manifiestan las dificultades de lectoescritura en los estudiantes evaluados con la prueba de pseudopalabras?"
FULL[120] = "¿Qué estrategias o intervenciones han servido para mejorar la lectura y la escritura?"
FULL[121] = "¿Qué relación hay entre los errores de escritura (omisiones, inversiones, sustituciones) y los resultados en la lectura de pseudopalabras?"
FULL[122] = "Este estudio se justifica porque en las aulas hacen falta diagnósticos tempranos y estrategias pensadas para las dificultades concretas de cada estudiante. Con el análisis buscamos ofrecer referentes, conceptuales y prácticos, que ayuden a enseñar mejor a leer y escribir, ya que de eso depende buena parte del rendimiento académico, de la inclusión y de la participación social. Queremos, en últimas, aportar herramientas para comprender, evaluar y mejorar la lectura y la escritura en las escuelas de hoy."

# --- Planteamiento del problema
FULL[153] = "Leer y escribir son la base de casi todo lo que se aprende en la escuela: por ahí pasan el acceso al conocimiento, la comprensión del mundo y la posibilidad de participar en la cultura escrita. Aun así, en muchos contextos, y sobre todo en América Latina, los estudiantes siguen mostrando dificultades serias en lectura y escritura que terminan afectando su rendimiento. Se ven en errores repetidos al decodificar, en una conciencia fonológica débil, en problemas de comprensión y en textos escritos pobres. Ante este panorama nos preguntamos qué hay detrás de esas dificultades y cómo pueden atenderse desde la pedagogía, teniendo en cuenta el contexto de cada estudiante."
FULL[154] = "Investigaciones recientes apuntan a varios factores que han hecho más difícil este aprendizaje: la dislexia, la lateralidad cruzada, las brechas socioeconómicas, la falta de formación docente y los efectos de la pandemia. Muchos maestros, además, no tienen herramientas para detectar a tiempo fallas en la ruta fonológica ni para intervenir de forma adecuada. El resultado es una distancia grande entre lo que se espera que un estudiante lea y escriba y lo que de verdad logra."
FULL[155] = "El problema que nos ocupa, entonces, es cómo se combinan los factores neurocognitivos, pedagógicos y socioculturales en la aparición de estas dificultades, y hasta qué punto una prueba diagnóstica de pseudopalabras ayuda a detectar fallas concretas en la decodificación y en la conciencia fonológica. De ahí salen las preguntas que orientan la investigación, con la idea de que sus respuestas sirvan para diseñar mejores estrategias de enseñanza y de acompañamiento."

# --- Antecedentes
FULL[172] = "Varias investigaciones coinciden en que aprender a leer no depende solo de lo que se enseña en clase. También intervienen procesos neurocognitivos como la memoria de trabajo, la velocidad de procesamiento, la conciencia fonológica y las rutas de acceso al léxico. En los estudios sobre dislexia aparecen dificultades para decodificar y reconocer patrones fonológicos incluso en estudiantes que nunca habían sido diagnosticados, y por eso se insiste en evaluar temprano y con instrumentos adecuados."
FULL[173] = "Los trabajos revisados también relacionan la lateralidad cruzada y la dislexia con errores al leer y al escribir. Según varios autores, de ahí pueden venir omisiones, sustituciones o inversiones de letras, además de problemas para automatizar la lectura. Otros hallazgos recientes muestran cuánto golpeó la pandemia a la alfabetización, en especial en contextos vulnerables, donde la falta de recursos tecnológicos y pedagógicos ahondó las brechas."
FULL[174] = "En cuanto a la formación docente, los estudios muestran una distancia considerable entre lo que se necesita en el aula y lo que los maestros saben sobre alfabetización. Vistos en conjunto, estos antecedentes dejan claro que las dificultades de lectoescritura no aparecen solas: responden a varios factores a la vez, y hay que analizarlos con detalle para intervenir mejor."
FULL[176] = "Este artículo trata la dislexia en la educación básica y, en particular, su relación con la lateralidad en la escritura. Las autoras estudian cómo la lateralidad cruzada lleva a confundir grafemas como b-d y p-q, lo que entorpece el aprendizaje de la lectoescritura. Para el diagnóstico usaron instrumentos psicopedagógicos como el PROLEC-R, el WISC IV, el Test de Harris de lateralidad y pruebas de discriminación fonológica."
FULL[177] = "En el caso estudiado, la paciente tiene una lateralidad cruzada mal afirmada, disgrafía fonológica y dificultades para identificar letras y signos de puntuación. Duarte-Hernández y Pérez-Mendoza (2020) señalan que la lateralidad suele estar definida hacia los 6 años. Aunque su coeficiente intelectual está por encima del promedio (CI = 115), la niña lee y escribe con lentitud. Para las autoras, esto indica que la lateralidad pesa en el desarrollo de la lectura y la escritura de los niños con dislexia, algo a lo que la escuela todavía presta poca atención (Medina, 2020; Cameron, 2021)."
FULL[178] = "El estudio recomienda intervenciones psicopedagógicas especializadas que trabajen la conciencia fonológica, la discriminación auditiva y la visomotricidad, porque eso podría mejorar tanto la escritura como la lectura (Santana et al., 2021). Trabajar esas áreas es, según las autoras, el camino para que los niños con dislexia superen sus dificultades."
FULL[179] = "Desde una mirada crítica, el análisis del caso es detallado, pero se limita a una sola paciente, lo que impide generalizar los hallazgos. Además, aunque se usaron pruebas diagnósticas reconocidas, no hubo seguimiento en el tiempo para medir el efecto de las intervenciones en la lectura y la escritura a largo plazo (Gutiérrez & Díez, 2018). Tampoco se discute cómo influyen la escuela y la familia en la dislexia, un aspecto que podría ser decisivo en la evolución de estos trastornos (Snowling et al., 2020)."
FULL[180] = "En la práctica, el artículo es útil para entender la relación entre dislexia y lateralidad y para ver por qué importan un diagnóstico preciso y un trabajo ajustado a cada estudiante. A los docentes les sirve como guía para reforzar la conciencia fonológica y las habilidades visomotoras, y así reducir el efecto de la dislexia en el rendimiento escolar."
FULL[193] = "El ensayo también se fija en cómo el aprendizaje se volvió más individual en los entornos digitales. El encierro y la dependencia de las clases en línea rompieron en parte la relación entre docentes y alumnos, y con ello se resintieron la colaboración y la participación. McLuhan ya advertía que los medios electrónicos no solo amplían el acceso a la información, sino que cambian la forma en que una cultura se percibe y se transmite, y eso obliga a repensar la educación (McLuhan, 1969)."
FULL[194] = "Al cierre, Tomás piensa en el futuro de la educación y de la lectoescritura en la era digital y retoma a Sven Birkerts (Elegía a Gutenberg, 1994), quien advierte que la tecnología puede transformar la conciencia humana y la cultura. El ensayo no propone soluciones definitivas, pero sí insiste en desarrollar competencias de lectura y escritura para los entornos digitales y en enseñar a usar la tecnología con sentido crítico."
FULL[220] = "Domínguez Vázquez (2023) presenta una intervención psicopedagógica para mejorar la lectoescritura de estudiantes de segundo de primaria en riesgo de exclusión social. Trabaja con un enfoque de investigación-acción y un diseño cuasiexperimental, es decir, uno en el que los participantes no se asignan a los grupos al azar (Arnau, 1995). La autora reporta mejoras importantes en comprensión lectora, escritura, conciencia fonológica y motivación hacia la lectura y la escritura."
FULL[221] = "En lo teórico, el estudio se enmarca en el Objetivo de Desarrollo Sostenible de la ONU sobre educación inclusiva y de calidad (Naciones Unidas, 2015). Se conecta, además, con trabajos que piden enfoques educativos adaptados para mejorar la alfabetización en entornos desfavorecidos (UNESCO, 2017; Save the Children, 2018)."
FULL[222] = "Lo más interesante es cómo está armado el programa. Incluye actividades multisensoriales y lúdicas, como lectura interactiva, reconocimiento de fonemas y escritura creativa. Esa mezcla recoge enfoques pedagógicos actuales que ya han dado buenos resultados en la alfabetización infantil (Snow et al., 2018; Dickinson et al., 2019)."
FULL[223] = "El artículo no oculta sus dificultades, y la mayor fue el alto ausentismo en el grupo intervenido. Los estudios sobre deserción escolar muestran que faltar a clase con frecuencia frena la adquisición de competencias básicas (Suárez-Álvarez & Fernández-Alonso, 2018). La autora propone contar con personal especializado, entre ellos profesores de servicios a la comunidad (PSC), en línea con lo que se sabe sobre el peso del apoyo institucional en el rendimiento (Downer et al., 2017)."
FULL[224] = "La investigación mezcla observación cualitativa con mediciones cuantitativas del progreso en cinco áreas: comprensión lectora, escritura, reconocimiento de palabras, conciencia fonológica y motivación. Medir a la vez lo cognitivo y lo afectivo es lo que recomienda la investigación educativa para la alfabetización infantil (González-Castro & Núñez, 2016; Creswell, 2014)."
FULL[225] = "El estudio tiene límites. No hubo un grupo de control aleatorizado, así que sus resultados no pueden extenderse sin más a otras poblaciones. Y como todo ocurrió en una sola escuela, cuesta saber si funcionaría igual en instituciones distintas. A su favor, el diseño es flexible y permite ir ajustando la intervención según lo que necesiten los estudiantes."
FULL[226] = "En suma, Domínguez Vázquez (2023) muestra que las intervenciones específicas sí mejoran la alfabetización en contextos de riesgo social. Le faltan una evaluación a largo plazo y una solución al ausentismo, pero sus resultados son buenos y apoyan el uso de enfoques inclusivos. Es una referencia útil para quien quiera estudiar la relación entre educación y equidad."

# --- Justificación y objetivos
FULL[229] = "Leer y escribir bien es indispensable para que un estudiante avance en lo académico, en lo cognitivo y en lo social: es lo que le permite acceder al conocimiento, interpretar lo que pasa a su alrededor y comunicarse. Sin embargo, las investigaciones siguen encontrando dificultades de lectura y escritura en las escuelas, sobre todo donde se cruzan la dislexia, la lateralidad cruzada, las brechas socioculturales y una formación docente insuficiente. Por eso queremos entender mejor qué interviene en la adquisición de la lectoescritura, con la idea de aportar a que se enseñe mejor."
FULL[230] = "Escogimos este tema porque, aunque está bien documentado, en las instituciones educativas todavía se le presta poca atención: las dificultades de lectura y escritura se detectan tarde y casi nunca hay estrategias pensadas para el contexto de cada grupo. Como la lectura de pseudopalabras sirve para evaluar la ruta fonológica y la decodificación, decidimos diseñar y analizar una prueba diagnóstica que nos dejara ver con más precisión dónde fallan los estudiantes."
FULL[231] = "El trabajo reúne en una misma revisión miradas neurocognitivas, pedagógicas y socioculturales, lo que da una visión más completa y actual de la lectoescritura. Además, deja insumos conceptuales y metodológicos que pueden servir a otras investigaciones, a programas de intervención y a la formación de docentes. Con todo esto buscamos entender mejor qué influye en la lectura y la escritura y promover prácticas más inclusivas, oportunas y apoyadas en evidencia."
FULL[238] = "Analizar qué factores neurocognitivos, pedagógicos y socioculturales intervienen en la enseñanza y el aprendizaje de la lectoescritura, a partir de una revisión teórica y de la aplicación de una prueba diagnóstica de pseudopalabras."
LEAD[242] = "los fundamentos teóricos sobre conciencia fonológica, decodificación y rutas lectoras, así como las dificultades que se asocian con la dislexia y la lateralidad cruzada."
LEAD[243] = " los factores socioculturales, económicos y pedagógicos que inciden en el desarrollo de la lectoescritura, entre ellos los efectos de la pandemia y los vacíos en la formación docente."
LEAD[244] = " una prueba diagnóstica de pseudopalabras, centrada en la ruta fonológica, para aplicarla con los estudiantes."

# --- Marco teórico
FULL[248] = "Partimos de entender la lectoescritura como un proceso cognitivo y pedagógico muy complejo, que va mucho más allá de reconocer signos gráficos: en él se juntan la decodificación, la comprensión, la memoria operativa y la construcción de significado. Dentro de ese conjunto, la conciencia fonológica ocupa un lugar central, porque es la que le permite al estudiante manipular los sonidos del habla y relacionar grafemas con fonemas. Aguirre-Medrano y González-López (2021) muestran que las dificultades en esta área, como las que se ven en la dislexia o en los problemas de discriminación auditiva, aparecen como errores típicos de la ruta fonológica. Para evaluar esa ruta por separado y con precisión, las pruebas de pseudopalabras son muy útiles: como no significan nada, el lector no puede apoyarse en el reconocimiento visual ni en la memoria léxica y tiene que aplicar las reglas de conversión grafema-fonema."
FULL[249] = "A esa mirada cognitiva le sumamos una pedagógica y de contexto. Trabajos recientes como los de Domínguez Vázquez (2023) y López Rivas (2024) muestran que el éxito de la alfabetización depende mucho del entorno. La vulnerabilidad social, las brechas tecnológicas que la pandemia hizo más grandes y el acceso desigual a materiales de lectura condicionan lo que un niño puede aprender, y eso exige metodologías flexibles y ajustadas a cada contexto. La formación de los docentes también pesa. Morales Londoño (2018) y Giraldo Gaviria y Caro Lopera (2022) critican las prácticas tradicionales y piden fortalecer la alfabetización académica de los maestros, para que puedan diseñar intervenciones a la medida de sus estudiantes. El marco teórico une, entonces, la dimensión neurocognitiva de la lectura con las variables socioculturales y didácticas que la rodean. La idea de fondo es que una buena intervención empieza por un diagnóstico preciso, como el que permiten las pruebas de pseudopalabras, y sigue con estrategias que respondan a lo que necesita cada estudiante y a las condiciones de su entorno."
FULL[253] = "La lectoescritura reúne habilidades cognitivas, lingüísticas y motoras que se necesitan para interpretar, producir y comprender textos. No se trata solo de reconocer símbolos: implica decodificar, comprender, sostener la atención, usar la memoria de trabajo y construir significado. Por eso varios autores la consideran una base del desempeño académico y de la participación social (Morales Londoño, 2018)."
FULL[254] = "Morales Londoño (2018) revisa, en particular, las ideas equivocadas que circulan sobre la lectoescritura, el papel del docente y la complejidad de este aprendizaje, tanto en lo pedagógico como en lo cognitivo."
FULL[256] = "La conciencia fonológica es la capacidad de identificar y manipular los sonidos del habla, y de ella depende en gran parte que el niño logre relacionar de manera estable grafemas y fonemas al aprender a leer. Su papel es todavía más visible en estudiantes con dislexia, disgrafía fonológica o problemas de discriminación auditiva, como lo documentan Aguirre-Medrano y González-López (2021) al analizar la relación entre lateralidad, conciencia fonológica y desempeño lector."
FULL[257] = "Pruebas como el PROLEC-R y las de discriminación fonológica permiten detectar los errores típicos de la ruta fonológica: omisiones, sustituciones, inversiones y segmentaciones incorrectas (Aguirre-Medrano & González-López, 2021; Duarte-Hernández & Pérez-Mendoza, 2020)."
FULL[258] = "Las pseudopalabras, que forman parte de la batería PROLEC-R y que retomamos de forma ampliada en nuestra prueba diagnóstica, son una buena herramienta para evaluar la decodificación, porque obligan al estudiante a aplicar reglas fonológicas sin apoyarse en la memoria léxica. Con este tipo de estímulos se elimina el factor de memorización y aparece el nivel real de dominio de las reglas fonológicas y grafémicas, lo que deja ver de manera directa cómo funciona la ruta fonológica al leer y al escribir."
FULL[262] = "López Rivas (2024), por su parte, estudia los efectos de la pandemia en la enseñanza de la lectoescritura y muestra cómo las brechas tecnológicas y sociales afectaron la alfabetización en zonas urbanas y rurales. El acceso limitado a la tecnología o el nivel educativo de los padres tuvieron efectos distintos según el caso, y eso hace urgente contar con metodologías flexibles y adaptadas a cada contexto."
FULL[264] = "La calidad de la enseñanza de la lectura y la escritura depende también de cómo se prepara a los docentes. Giraldo Gaviria y Caro Lopera (2022) insisten en fortalecer la alfabetización académica desde la formación inicial de los maestros. Morales Londoño (2018) coincide en ello cuando afirma que la enseñanza de la lectoescritura en Colombia arrastra fallas por concepciones equivocadas, prácticas tradicionales y poca actualización profesional."
FULL[266] = "Aprender a leer no depende solo de procesos internos. El contexto familiar, las oportunidades de acceder a textos, las metodologías de los docentes y las condiciones socioculturales influyen, y mucho. La pandemia amplió las brechas, sobre todo para los estudiantes con poco acceso a recursos tecnológicos, a quienes les costó más sostener su proceso de alfabetización (International Business Machines [IBM], 2013)."
FULL[267] = "Esto dejó en evidencia que se necesitan programas de apoyo, acompañamiento y seguimiento escolar para que el aprendizaje no se interrumpa."
FULL[269] = "Las pruebas de pseudopalabras sirven para evaluar cómo funciona la ruta fonológica. Como esos estímulos no forman parte del léxico que el lector conoce, lo obligan a aplicar las reglas de conversión grafema-fonema. Así es más fácil detectar dificultades de decodificación y de conciencia fonológica, que Aguirre-Medrano y González-López (2021) consideran decisivas en estudiantes con dislexia o con problemas de discriminación auditiva."
FULL[270] = "En la misma línea, Duarte-Hernández y Pérez-Mendoza (2020) explican que las dificultades visomotoras y las confusiones entre grafemas se manifiestan en omisiones, sustituciones, inversiones y segmentaciones inadecuadas. Esos errores suelen salir a la luz cuando el estudiante tiene que leer algo que no puede resolver con la memoria visual o léxica."
FULL[271] = "La batería PROLEC-R, que se aplicó en este estudio, incluye la lectura de pseudopalabras justamente para evaluar esta ruta y observar qué tanto domina el estudiante las reglas fonológicas y con cuánta precisión decodifica."
FULL[272] = "Analizar los errores que aparecen en esta tarea da pistas concretas para diseñar intervenciones a la medida, dirigidas a mejorar la decodificación, la discriminación fonológica y el reconocimiento preciso de las unidades gráficas."
FULL[288] = "Como el estudio buscaba analizar a fondo las dificultades de lectoescritura de diez estudiantes a partir de la aplicación de la prueba PROLEC-R, optamos por un enfoque cualitativo. Nos interesaba comprender cómo lee cada uno y qué tipo de errores comete, e interpretar los resultados a la luz de sus condiciones particulares."

# --- Resultados
FULL[319] = "Esto importa para analizar la ruta fonológica, porque una pseudopalabra obliga a decodificar sin la ayuda de la memoria léxica. Los cambios que hicieron los estudiantes reflejan, por tanto, distintos grados de consolidación en la conversión grafema-fonema. No todos se comportaron igual, así que los resultados hay que leerlos como heterogéneos y no como una dificultad del grupo entero."
FULL[321] = "Las dificultades, entonces, no aparecen solo al leer. También surgen en el camino inverso, cuando el estudiante tiene que pasar de lo que oye a lo que escribe. Escribir al dictado una pseudopalabra exige retener la secuencia de sonidos, reconocer sus unidades y elegir los grafemas correctos. Las transformaciones encontradas muestran que la representación y la escritura de estos estímulos todavía son inestables."
FULL[323] = "Comprensión y conciencia fonológica: La tercera actividad incluyó preguntas para identificar sonidos iniciales, finales e internos, reconocer terminaciones semejantes y separar en sílabas."
FULL[324] = "Cuando se les preguntó por el sonido inicial de “gropel”, unos estudiantes dijeron “G” y otros “Gro”, es decir, un segmento más largo. Lo mismo pasó en otras preguntas. Para el sonido final de “finod” hubo quienes respondieron “D” y quienes respondieron “Not” o “Nod”. Y para el sonido interno de “lumep” aparecieron respuestas tan distintas como “M”, “Met”, “Ume”, “Me” y “Um”."
FULL[325] = "El desempeño cambia, pues, según la operación fonológica que se pida. Algunos estudiantes logran aislar la unidad sonora exacta; otros responden con fragmentos más largos. No sería correcto decir que les falta conciencia fonológica en general. Lo que se ve son dificultades puntuales para aislar y reconocer ciertas unidades sonoras."
FULL[328] = "Fluidez lectora en frases: La cuarta actividad consistió en leer pseudopalabras dentro de oraciones. En general, los estudiantes leyeron las frases sin mayores tropiezos. Reprodujeron, por ejemplo, “El drumo saltó sobre la mesa”, “María compró un teniq azul” y “El perro jugaba con el bapo en el parque”, aunque en algunos casos hubo cambios menores."
FULL[329] = "El dato es interesante, porque sugiere que el desempeño depende del contexto en que aparece el estímulo. Leída sola, la pseudopalabra le genera cambios a algunos estudiantes; dentro de una frase, la lectura parece más estable. Es posible que el contexto lingüístico les dé pistas adicionales al leer."
FULL[330] = "Asociación grafema–fonema: La quinta actividad buscaba ver directamente cómo relacionan los estudiantes las letras con los sonidos iniciales. En algunos registros identificaron bien el sonido inicial de “zunel” como /Z/ y la grafía inicial de “quarim” con “q” o “qua”. En otros hubo respuestas más amplias o imprecisas, como “Zu”, “au” y “ua”. El estudiante 9, por ejemplo, respondió “/Zu/” para “zunel” y “ua” para “quarim”, mientras que otros compañeros identificaron con más precisión la “Z” y la “q”."
FULL[331] = "Hay, entonces, distintos niveles de consolidación de la correspondencia grafema-fonema. Como aparecieron tanto respuestas correctas como incorrectas, no se puede hablar de una dificultad general de todo el grupo."
FULL[339] = "Transcripción de prueba."

# --- Análisis de la transcripción
FULL[673] = "El objetivo general de la investigación era analizar los factores neurocognitivos, pedagógicos y socioculturales que intervienen en la enseñanza y el aprendizaje de la lectoescritura, mediante la revisión teórica y la aplicación de una prueba de pseudopalabras. De forma específica, nos propusimos identificar los fundamentos sobre conciencia fonológica, decodificación, rutas lectoras y dificultades asociadas a la dislexia y la lateralidad cruzada, y diseñar una prueba centrada en la ruta fonológica."
FULL[676] = "En general, los diez estudiantes mostraron niveles de desempeño distintos. Al leer y escribir pseudopalabras hubo modificaciones, sustituciones, omisiones y cambios de algunos segmentos, pero no en todos por igual ni con la misma intensidad. Algunos se mantuvieron más estables en ciertas tareas, sobre todo en la segmentación silábica y en reconocer terminaciones parecidas; otros variaron más al identificar sonidos iniciales, finales o intermedios."
FULL[677] = "También vimos que el desempeño de un mismo estudiante podía cambiar de una actividad a otra. Las pseudopalabras aisladas produjeron más modificaciones en algunos registros, mientras que las frases que las contenían se leyeron de forma bastante estable. Esto hace pensar que el contexto de la tarea influye en la ejecución, aunque la transcripción no registra tiempos, velocidad ni número exacto de errores que permitan compararlo estadísticamente."
FULL[678] = "Por eso los resultados no deben leerse como prueba de una dificultad general en todos los procesos de lectoescritura. Lo que muestran es un desempeño desigual: algunos estudiantes tienen dificultades en componentes concretos de la ruta fonológica y de la conciencia fonológica, pero conservan otras habilidades de análisis sonoro y de lectura."
FULL[682] = "Lo que se ve aquí no es que los estudiantes no puedan leer las pseudopalabras, sino que no siempre convierten con precisión lo escrito en sonidos. Saben que tienen delante algo que deben pronunciar, pero al hacerlo cambian algunas letras, sonidos o segmentos."
FULL[683] = "Esto encaja con el marco teórico, donde planteamos que las dificultades de conciencia fonológica y de discriminación auditiva se manifiestan como errores en la ruta fonológica, y que las pseudopalabras sirven para detectar problemas de decodificación porque obligan a aplicar reglas grafema-fonema sin recurrir al vocabulario ya aprendido."
FULL[684] = "La ejecución de los estudiantes, por tanto, es coherente con la teoría de la ruta fonológica. Pero hay que cuidarse de no ir más lejos de lo que muestran los datos. Que un estudiante cambie una pseudopalabra no quiere decir que tenga dislexia. Lo único que se puede afirmar es que, en esa tarea, tuvo dificultades o imprecisiones al decodificar estímulos desconocidos."
FULL[685] = "La distinción no es menor. El resultado es un comportamiento que se puede observar; la teoría ayuda a interpretarlo; el diagnóstico de una condición clínica, en cambio, exige otros procedimientos. Por eso usamos estos resultados para señalar posibles dificultades y no para asignar una categoría diagnóstica."
FULL[689] = "Con la escritura pasa algo parecido. Las dificultades aparecen también cuando hay que ir del sonido a la letra: para escribir al dictado una pseudopalabra, el estudiante tiene que retener y manipular la secuencia sonora, distinguir sus partes y elegir los grafemas adecuados."
FULL[690] = "Al comparar las dos tareas surge una observación. Si un estudiante altera una misma pseudopalabra al leerla y al escribirla, cabe pensar que su representación fonológica no es estable o que le cuesta pasar del código escrito al sonoro y viceversa. Esta hipótesis es coherente con nuestro marco teórico, que pone la conciencia fonológica y la conversión grafema-fonema en el centro de la alfabetización."
FULL[691] = "La escritura, eso sí, añade complejidad. Escribir algo distinto de la palabra objetivo no remite necesariamente a un solo tipo de error: puede tener que ver con la percepción auditiva, con la memoria inmediata de la secuencia, con la representación fonológica, con el conocimiento ortográfico o con la elección de grafemas. Por eso describimos los resultados de manera concreta, sin atribuir cada cambio a una única causa."
FULL[695] = "Con el sonido final de “finod” pasó algo parecido. Unos respondieron bien, “D”; otros dijeron “Not” o “Nod”. “Not” aparece en el estudiante 3 y “Nod” en el estudiante 9.\nLo mismo se vio con el sonido interno de “lumep”. Algunos dieron la respuesta esperada, “M”, y otros produjeron formas más largas, como “Met”, “Ume” o “Me”.\nDe aquí sale una distinción importante. Los estudiantes parecen más seguros cuando tienen que reconocer una estructura global o separar en sílabas, y vacilan más cuando deben aislar un sonido concreto dentro de una pseudopalabra."
FULL[696] = "Es uno de los hallazgos más interesantes de la prueba. La segmentación de “trunal” como “Tru-nal” se repite correctamente en los registros; la dieron, por ejemplo, los estudiantes 2, 3, 4, 5, 7, 8 y 9.\nNo sería correcto, entonces, hablar de una dificultad general en toda la conciencia fonológica. Los datos muestran un desempeño desigual según el nivel de procesamiento que pide cada tarea: los estudiantes resuelven bien algunas, en particular la segmentación silábica y el reconocimiento de terminaciones parecidas, y les cuesta más aislar sonidos específicos."
FULL[700] = "La conclusión es que el dominio de las habilidades fonológicas varía entre los estudiantes, y eso es coherente con ver la lectoescritura como un proceso complejo en el que varias habilidades trabajan juntas."
FULL[701] = "La cuarta actividad, de fluidez lectora con pseudopalabras en frases, mostraba qué pasaba cuando esas palabras inventadas aparecían dentro de oraciones con sentido. Usamos, entre otras, “El drumo saltó sobre la mesa”, “María compró un teniq azul” y “El perro jugaba con el bapo en el parque”. Según la transcripción, los estudiantes leyeron las frases de forma bastante estable, con algunos cambios menores, sobre todo en la forma del verbo o en la reproducción exacta de la oración."
FULL[702] = "En el estudiante 9, por ejemplo, las frases salen casi idénticas a las originales. Lo mismo se ve en otros registros: los estudiantes leen con relativa continuidad las frases que llevan pseudopalabras."
FULL[703] = "Aquí aparece un contraste con la lectura aislada. Estudiantes que alteraban algunas pseudopalabras cuando las leían solas se desenvolvieron mejor cuando esas mismas palabras venían dentro de una oración."
FULL[704] = "Una explicación posible es que el contexto sintáctico y semántico de la frase ayuda a leer. Pero hay que tomarla con cautela, porque la transcripción no registra velocidad, pausas, tiempo de lectura ni errores contados. Con estos datos no se puede concluir estadísticamente que se lea mejor en contexto que de forma aislada."
FULL[705] = "Sí se puede afirmar que la ejecución no fue igual en todas las tareas. Las dificultades se notaron más al manipular pseudopalabras sueltas y en algunas preguntas de análisis fonológico; la lectura de frases fue más estable."
FULL[706] = "El resultado muestra que la lectura depende de lo que cada actividad exige. Leer una pseudopalabra sola obliga a decodificar de forma directa, mientras que dentro de una frase el lector cuenta con pistas del contexto."
FULL[707] = "La quinta actividad, por último, analizaba de manera directa la relación entre los estímulos escritos y los sonidos iniciales, es decir, la correspondencia grafema-fonema, uno de los conceptos centrales del trabajo."
FULL[708] = "En algunos registros los estudiantes identificaron bien “zunel” con /Z/ y reconocieron la letra o la combinación inicial de “quarim”. En otros respondieron “Zu” o “ua”, señal de que no todos aislaron con precisión la unidad que se les pedía. El estudiante 9 contestó “/Zu/” para “zunel” y “ua” para “quarim”, y el estudiante 7 también dijo “/Zu/” y “au”. Otros, en cambio, identificaron la “Z” y la “q” sin problema."
FULL[709] = "Con esto el análisis gana solidez, porque une lo que dice el marco teórico con lo que la prueba efectivamente registró. Si leer pseudopalabras exige aplicar reglas de conversión grafema-fonema, las respuestas imprecisas de esta actividad son una evidencia válida para describir dificultades en esa correspondencia."
FULL[710] = "Otra vez, sin embargo, no hay que generalizar. Que algunos estudiantes se equivocaran no significa que toda su correspondencia grafema-fonema esté comprometida. Hubo respuestas correctas e incorrectas, así que lo más justo es hablar de un grado variable de consolidación."
# En la transcripción solo hay un Estudiante 8 (del 1 al 10); la frase sobre un registro duplicado no corresponde
FULL[719] = "El estudiante 8 presenta igualmente modificaciones en lectura y escritura y respuestas como “Gro”, “Nod” y “Me”, pero conserva la respuesta correcta en semejanza final y segmentación silábica."
BORRAR = [720]
FULL[724] = "En este trabajo se entiende la lectoescritura como un proceso cognitivo y pedagógico complejo que involucra decodificación, comprensión, memoria y construcción de significado. Dentro de esta perspectiva, la conciencia fonológica ocupa un lugar central porque permite manipular los sonidos y establecer correspondencias entre grafemas y fonemas."
FULL[726] = "En el marco teórico también retomamos a Aguirre-Medrano y González-López (2021), quienes relacionan las dificultades de lectoescritura con problemas de conciencia fonológica, de discriminación auditiva y con ciertos patrones de error. Allí señalamos que estas dificultades se manifiestan como errores de la ruta fonológica y que las pseudopalabras permiten observarlos."
FULL[729] = "Aquí, sin embargo, hay una diferencia importante entre lo que plantea nuestro marco teórico y lo que la transcripción alcanza a demostrar. En el marco se mencionan confusiones entre grafemas como b-d y p-q, relacionadas con la lateralidad y con lo visomotor. La prueba que aplicamos, en cambio, se centra en pseudopalabras, identificación de sonidos, escritura al dictado, segmentación y asociación grafema-fonema, y no incluye una evaluación específica de lateralidad."
FULL[730] = "Por lo tanto, no sería correcto afirmar que la prueba demostró lateralidad cruzada. A lo sumo, algunos resultados podrían ser compatibles con las dificultades perceptivas o grafémicas que describe la literatura, pero la lateralidad necesita una evaluación propia. De hecho, el antecedente que citamos usó otros instrumentos, como el Test de Harris de lateralidad, además del PROLEC-R."
FULL[731] = "Por eso no decimos que la prueba “confirmó” la lateralidad cruzada. Esta variable forma parte del marco conceptual y, para contrastarla, haría falta aplicar instrumentos específicos."
FULL[732] = "La dislexia es otro de los conceptos importantes de nuestro marco, en el que revisamos investigaciones sobre dificultades lectoras, lateralidad, conciencia fonológica y discriminación auditiva."
FULL[734] = "Otro componente son los factores pedagógicos, sociales y del contexto. En el trabajo planteamos que las dificultades de lectoescritura no dependen solo de procesos internos, sino que se relacionan con las oportunidades educativas, los recursos, las metodologías docentes, las condiciones familiares y los efectos de la pandemia. Esto ayuda a entender el problema general, pero hay que separarlo de lo que arrojó la prueba."
FULL[737] = "Al contrastar los resultados con los objetivos, la correspondencia más clara es con el objetivo de identificar los fundamentos teóricos sobre conciencia fonológica, decodificación y rutas lectoras. La prueba permitió observar directamente la lectura y la escritura de pseudopalabras, la identificación de sonidos y la correspondencia grafema-fonema, que son los procesos que considerábamos centrales. El objetivo de diseñar una prueba diagnóstica centrada en la ruta fonológica también se cumplió, al menos en parte, porque usamos pseudopalabras precisamente para que los estudiantes no se apoyaran en palabras conocidas: estos estímulos eliminan el apoyo del vocabulario memorizado y obligan a aplicar las reglas grafema-fonema."
FULL[739] = "Teniendo en cuenta lo anterior, del análisis de los diez registros se desprenden varios hallazgos principales."

# --- Discusión
FULL[749] = "Al discutir los resultados encontramos una correspondencia clara entre los referentes teóricos y varios de los comportamientos observados en la prueba, sobre todo en lo que tiene que ver con la conciencia fonológica, la ruta fonológica, la decodificación y la conversión grafema-fonema."
FULL[750] = "Según el marco teórico, las pseudopalabras sirven para evaluar la ruta fonológica porque obligan a usar las reglas que conectan grafemas y fonemas. Y fueron justamente las pseudopalabras las que dejaron ver la mayor cantidad de modificaciones y de respuestas variables."
FULL[751] = "La prueba cumplió así un papel importante en el trabajo: nos permitió pasar de la discusión teórica a observar, en concreto, cómo se enfrentan los estudiantes a estímulos lingüísticos desconocidos."
FULL[752] = "La comparación también mostró fortalezas. Que los estudiantes separen bien en sílabas y reconozcan palabras con terminaciones parecidas indica que sí tienen habilidades fonológicas. Lo adecuado, por tanto, no es decir que “no tienen conciencia fonológica”, sino que tienen dificultades puntuales en ciertas operaciones de análisis fonológico."
FULL[753] = "Este matiz hace la discusión más precisa y menos determinista. A eso se suma que el desempeño en lectura y escritura cambia según la tarea: hay estudiantes que alteran pseudopalabras aisladas y, sin embargo, leen con bastante estabilidad las frases que las contienen. El contexto de la tarea influye en la ejecución."
FULL[754] = "Los resultados respaldan, entonces, la idea de que la lectoescritura es un proceso complejo y no una sola habilidad. Alguien puede tener dificultades en un componente y, a la vez, manejar bien otros."
FULL[755] = "En el trabajo también planteamos que las dificultades lectoras pueden estar ligadas a factores pedagógicos y del contexto. Los antecedentes hablan de prácticas tradicionales, de vacíos en la formación docente y de los efectos de la pandemia. Con los datos de la prueba, sin embargo, no es posible establecer una relación causal entre esos factores y el desempeño de cada estudiante."
FULL[756] = "Por eso separamos lo que observamos directamente de lo que viene de la literatura. Esa distinción le da solidez a la investigación y evita leer los resultados más allá de lo que realmente permiten demostrar."

# --- Conclusiones
FULL[766] = "El análisis de la prueba de pseudopalabras nos lleva a concluir que los estudiantes evaluados tienen distintos niveles de consolidación en la decodificación, la conciencia fonológica y la correspondencia grafema-fonema. Los cambios que hicieron al leer y escribir pseudopalabras muestran que, frente a estímulos desconocidos, a algunos les cuesta mantener una correspondencia precisa entre letras y sonidos."
FULL[767] = "Leer pseudopalabras permitió observar de cerca los procesos ligados a la ruta fonológica, porque con estos estímulos casi no hay manera de apoyarse en palabras conocidas. Las sustituciones, omisiones y transformaciones que registramos son pistas útiles para detectar posibles dificultades de decodificación. Como no aparecieron por igual en todos, no se puede hablar de un único perfil lector en el grupo."
FULL[768] = "En la escritura al dictado, las transformaciones encontradas muestran que las dificultades también aparecen cuando hay que convertir lo que se oye en algo escrito. Lectura y escritura deben mirarse juntas, sin olvidar que cada una exige operaciones cognitivas y lingüísticas distintas."
FULL[769] = "La conciencia fonológica mostró un desempeño desigual. Algunos estudiantes identificaron sonidos iniciales, finales e internos; otros respondieron con segmentos más largos o distintos. La segmentación silábica y el reconocimiento de terminaciones parecidas fueron más estables. No hay, entonces, una ausencia general de conciencia fonológica, sino dificultades en ciertas operaciones de análisis sonoro."
FULL[770] = "La asociación grafema-fonema también varió de un estudiante a otro. Hubo respuestas precisas y otras en las que costó identificar la unidad gráfica o sonora pedida. La consolidación de estas correspondencias es variable y debe analizarse según las características de cada estudiante."
FULL[771] = "El desempeño, además, cambia según la tarea. Las frases con pseudopalabras se leyeron con relativa estabilidad, mientras que la lectura aislada produjo algunos cambios, lo que indica que el contexto lingüístico influye en la ejecución. Evaluar la lectoescritura exige, por eso, mirar distintas situaciones y niveles de procesamiento."

# --- Segunda pasada: párrafos marcados en parte por Turnitin o que el simulador aún puntúa alto
FULL[182] = "Giraldo Gaviria y Caro Lopera (2022) analizan a fondo la alfabetización académica y su efecto en la formación inicial de docentes en las Escuelas Normales Superiores (ENS) de Colombia. Su punto de partida es que enseñar a escribir textos académicos es indispensable en la formación de maestros, porque les abre la puerta a las comunidades discursivas y les ayuda a desarrollar competencias para investigar y argumentar."
FULL[191] = "Según el ensayo, adaptarse a la educación digital no dependerá tanto de los planes de estudio o de las políticas educativas como de la preparación técnica de estudiantes y docentes. El autor describe las barreras tecnológicas y pedagógicas de ese tránsito y muestra cómo la enseñanza en línea cambió la dinámica de las clases al llevar la lectura y la escritura a entornos digitales, algo que pide enfoques pedagógicos nuevos (Casillas Alvarado & Ramírez Martinell, 2018)."
FULL[192] = "Tomás lee el impacto de la pandemia con los lentes de McLuhan, para quien la aldea global es un espacio donde la tecnología moldea la percepción y el aprendizaje. Según McLuhan, los entornos digitales devuelven a la comunicación rasgos de la oralidad: al reintroducir lo auditivo y lo visual, se parecen a las prácticas comunicativas anteriores a la escritura fonética (McLuhan, 1962). Tomás advierte, de todos modos, que con la virtualidad se perdieron elementos pragmáticos propios de la clase presencial, como los gestos y la interacción en el aula."
FULL[200] = "El artículo tiene una estructura clara: introducción, fundamentación teórica, metodología, resultados y conclusiones. Se le podría pedir más claridad y cohesión, porque repite algunas ideas y deja apartados poco desarrollados. Además, aunque el título habla de lectoescritura, el texto termina tratando el proceso de enseñanza-aprendizaje en general, y eso genera cierta ambigüedad."
FULL[202] = "Morales Londoño (2018) estudia la calidad de la enseñanza de la lectoescritura en Colombia, con foco en la básica primaria. A partir de una revisión documental, analiza las dificultades de lectura y escritura que reflejan las pruebas SABER y PISA, los lineamientos del Ministerio de Educación Nacional (MEN) y las estrategias del gobierno para mejorar la calidad educativa."
FULL[316] = "Los resultados de la prueba de pseudopalabras nos dan una aproximación descriptiva a cómo leen y escriben diez estudiantes. El análisis es cualitativo y se basa en las respuestas registradas en cinco actividades: lectura de pseudopalabras, escritura al dictado, comprensión fonológica, fluidez lectora en frases y asociación grafema-fonema. Las diseñamos para observar, sobre todo, la decodificación, la conciencia fonológica y la conversión grafema-fonema."
FULL[317] = "Trabajar con pseudopalabras tenía sentido para lo que queríamos ver. Como no forman parte del vocabulario habitual de los niños, es difícil que las reconozcan de memoria, y entonces tienen que decodificar y convertir grafemas en fonemas. En la transcripción aparecen modificaciones, sustituciones, omisiones y cambios de algunos segmentos a lo largo de las actividades, aunque no en todos los participantes ni con la misma intensidad."
FULL[336] = "En resumen, encontramos siete cosas. Hubo modificaciones al leer pseudopalabras y transformaciones al escribirlas al dictado. La conciencia fonológica fue desigual entre los estudiantes, la segmentación silábica se mantuvo más estable y las terminaciones semejantes se identificaron de forma bastante consistente. En la asociación grafema-fonema hubo diferencias, y los perfiles individuales resultaron muy variados."
FULL[337] = "Las dificultades más claras están, por tanto, en ciertos procesos de decodificación, de análisis fonológico y de correspondencia grafema-fonema. Otras habilidades, como la segmentación silábica y el reconocimiento de finales parecidos, se mantienen más firmes."
FULL[671] = "Al analizar la transcripción encontramos que lo que hicieron los estudiantes coincide en buena medida con los referentes teóricos, sobre todo en conciencia fonológica, ruta fonológica y decodificación. Los errores al leer y escribir pseudopalabras, y en algunas tareas de identificación de sonidos y de asociación grafema-fonema, indican que varios estudiantes todavía no consolidan del todo los mecanismos para convertir grafemas en fonemas con precisión. Eso es lo que anticipaba el marco teórico, según el cual estas dificultades se manifiestan como sustituciones, omisiones, modificaciones y respuestas fonológicas imprecisas. Con todo, los resultados no alcanzan para diagnosticar dislexia ni para confirmar lateralidad cruzada, porque eso requiere evaluaciones específicas. La prueba funciona, más bien, como un instrumento descriptivo que ayuda a detectar posibles dificultades fonológicas y de decodificación."
FULL[672] = "La prueba de pseudopalabras nos dio una primera descripción de cómo se desempeñan los estudiantes en distintos procesos de lectura y escritura. Queríamos ver cómo reaccionaban ante estímulos que no estaban en su vocabulario y que, por eso mismo, los obligaban a decodificar, a usar la conciencia fonológica y a relacionar grafemas con fonemas. La elección se apoya en el marco teórico, donde planteamos que las pseudopalabras sirven para observar la ruta fonológica, ya que el estudiante no puede resolverlas recurriendo a palabras conocidas o a la memoria léxica."
FULL[680] = "La primera actividad, la lectura de pseudopalabras, permitió ver de forma directa cómo se enfrentan los estudiantes a palabras inventadas. Es una actividad clave en la investigación, porque una pseudopalabra no se puede reconocer como palabra familiar y obliga a usar las reglas de conversión grafema-fonema. Recordemos que, según el marco teórico, la conciencia fonológica es la que permite manipular los sonidos del habla y relacionar grafemas con fonemas, y la lectura de pseudopalabras deja ver la ruta fonológica de la manera más directa."
FULL[681] = "Al leer, los estudiantes modificaron varias pseudopalabras. El estudiante 2, por ejemplo, dijo “Zepa” en lugar de “Zepan” y “Consiul” frente a otra pseudopalabra del listado, entre otros cambios. En el estudiante 3 aparecen transformaciones como “Zepa”, “Trapi” y “Lused”. El estudiante 5 modificó algunos estímulos, como “Plerox”, y leyó otros de forma parecida al original. El caso más visible es el del estudiante 7, que respondió “Zapa”, “Trampin”, “Digan”, “Blused”, “Zolil”, “Flanit”, “Florir” y “Tutim”."
FULL[698] = "La actividad de escoger, entre “zopar”, “tamir” y “perar”, las pseudopalabras que terminaban igual dio resultados bastante estables. En los registros, los estudiantes eligieron “zopar – perar”.\nEsto importa porque muestra que su desempeño no es bajo en todas las dimensiones de la conciencia fonológica. Cuando la tarea es comparar, reconocen sin problema semejanzas sonoras globales."
FULL[699] = "Incluir las respuestas correctas en la discusión evita una lectura sesgada de los datos. Si solo se mostraran los errores, quedaría la imagen de un deterioro general que la transcripción no respalda. Lo que se ve, mirando todo, son estudiantes con dificultades en unas tareas y respuestas adecuadas en otras."
FULL[725] = "Los resultados de la prueba van en esa misma dirección. Cuando los estudiantes se enfrentan a estímulos que no conocen, aparecen modificaciones al leer y al escribir. Y esas modificaciones dicen mucho, precisamente porque con las pseudopalabras casi no se puede recurrir al reconocimiento automático de palabras conocidas."
FULL[727] = "Si contrastamos esa propuesta con lo que hicieron los estudiantes, la coincidencia es fuerte en la lectura y la escritura de pseudopalabras: las sustituciones y modificaciones observadas son compatibles con dificultades en la conversión fonológica. En ese sentido, los resultados son consistentes con los referentes teóricos revisados."
FULL[728] = "También hay correspondencia con Duarte-Hernández y Pérez-Mendoza (2020), que relacionan las dificultades visomotoras y las confusiones entre grafemas con errores de lectura y escritura."
FULL[736] = "Lo que sí podemos hacer es establecer una relación conceptual. El marco de la investigación reconoce que la lectoescritura se desarrolla dentro de un contexto educativo y social, y los resultados muestran ciertas dificultades en la ejecución. Para conectar directamente ambas cosas habríamos necesitado más información, por ejemplo entrevistas, observaciones de clase, cuestionarios a las familias, revisión de antecedentes académicos o análisis de las prácticas pedagógicas. Por eso presentamos los factores socioculturales como elementos de contexto que ayudan a interpretar el problema, no como causas que la prueba haya demostrado."
FULL[772] = "Frente a los referentes teóricos, la coincidencia más clara se da con lo que plantean sobre conciencia fonológica, ruta fonológica y decodificación. Lo observado concuerda con los antecedentes revisados sobre dificultades en estos procesos, en especial con lo que señalan Aguirre-Medrano y González-López (2021) sobre el peso de la conciencia fonológica y de la discriminación auditiva."
FULL[775] = "El principal aporte empírico de la investigación está, entonces, en la descripción de los procesos fonológicos y de decodificación que dejó ver la prueba de pseudopalabras. Con ella identificamos fortalezas y dificultades concretas, y a partir de ahí se ve la necesidad de estrategias pedagógicas diferenciadas para trabajar la conciencia fonológica, la decodificación, la correspondencia grafema-fonema y la escritura."

# Erratas puntuales en párrafos que no se reescriben (texto exacto -> corrección)
ERRATAS = {
    185: [("Molina en (2017)", "Molina (2017)")],
    186: [("cambios los curriculares", "cambios curriculares")],
    188: [("Gaviria y Lopera (2022)", "Giraldo Gaviria y Caro Lopera (2022)")],
}
BORRAR += [815]  # referencia de Morales Londoño (2018) repetida

W = qn("w:")


def limpiar_formato(run):
    rpr = run._r.rPr
    if rpr is None:
        return
    for tag in ("w:b", "w:bCs", "w:i", "w:iCs", "w:rStyle"):
        for el in rpr.findall(qn(tag)):
            rpr.remove(el)


def reemplazar(p, texto):
    runs = p.runs
    runs[0].text = texto
    limpiar_formato(runs[0])
    for r in runs[1:]:
        r._r.getparent().remove(r._r)


def reemplazar_tras_negrita(p, texto):
    # el primer run es el verbo del objetivo (en negrita por estilo o por formato)
    runs = p.runs
    runs[1].text = texto
    for r in runs[2:]:
        r._r.getparent().remove(r._r)


def errata(p, viejo, nuevo):
    for r in p.runs:
        if viejo in r.text:
            r.text = r.text.replace(viejo, nuevo)
            return
    texto = p.text
    assert viejo in texto, (viejo, texto[:80])
    reemplazar(p, texto.replace(viejo, nuevo))


def main(src, dst):
    d = docx.Document(src)
    P = d.paragraphs
    for i, t in FULL.items():
        reemplazar(P[i], t)
    for i, t in LEAD.items():
        reemplazar_tras_negrita(P[i], t)
    for i, cambios in ERRATAS.items():
        for v, n in cambios:
            errata(P[i], v, n)
    for i in sorted(BORRAR, reverse=True):
        el = P[i]._p
        el.getparent().remove(el)
    d.save(dst)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
